# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
SID: "ACbf9655e5dce076f5f08146511db291ec"
AUTH: "3e53b709f9ebab86ea4db344dc70fe99"
MY_APP_TEL: "6466814097"