# development:
#   access_key_id: AKIAIM67LCNDQ6I5ZQ2Q
#   secret_access_key: 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
#   bucket: sammypinterest
# production:
#   access_key_id: AKIAIM67LCNDQ6I5ZQ2Q
#   secret_access_key: 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
#   bucket: sammypinterest